#!/usr/bin/env python3
"""Generate run_baremetal.c from Karpathy's run.c by surgical replacement.

Why a generator instead of a hand-written port: we want to be able to say on
stage that the *math is unmodified*. Every transformer function -- rmsnorm,
softmax, matmul, RoPE, attention, the sampler -- is carried across byte for
byte. Only the I/O and allocation boundary is replaced, and this script is the
auditable record of exactly what changed.

What changes, and why:

  1. POSIX includes (fcntl/unistd/sys/mman) -- the board has no OS.
  2. read_checkpoint()  -- there is no filesystem; weights come from a linked blob.
  3. build_tokenizer()  -- same, plus a bump allocator instead of malloc.
  4. malloc_run_state() -- static arrays. 676 KB, sized for stories260K.
  5. time_in_ms()       -- no clock_gettime on bare metal.
  6. main()             -- no argv; fixed seed; unbuffered stdout.
  7. The tok/s line     -- upstream prints it with %f, and newlib's float printf
                           pulls in an enormous amount of code. Integer math.

    python3 tools/make_baremetal.py            # writes src/run_baremetal.c
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(ROOT, "vendor")
OUT_DIR = os.path.join(ROOT, "src")
RUN_C_URL = "https://raw.githubusercontent.com/karpathy/llama2.c/master/run.c"


def get_run_c() -> str:
    os.makedirs(VENDOR, exist_ok=True)
    p = os.path.join(VENDOR, "run.c")
    if not os.path.exists(p):
        print("  downloading run.c ...")
        urllib.request.urlretrieve(RUN_C_URL, p)
    return open(p, encoding="utf-8").read()


def cut(src: str, start_marker: str, replacement: str, end_marker: str) -> str:
    """Replace [start_marker .. end_marker) with replacement."""
    i = src.index(start_marker)
    j = src.index(end_marker, i)
    return src[:i] + replacement + src[j:]


# --------------------------------------------------------------------------- 1
HEADERS = '''/* run_baremetal.c -- GENERATED by tools/make_baremetal.py. Do not edit by hand.
 *
 * Karpathy's llama2.c with the operating system removed. Every neural-network
 * function below is byte-for-byte upstream; only I/O and allocation changed.
 *
 * Target: Nios II/f on the Intel FPGA University Program "DE10-Lite Computer".
 * No filesystem, no mmap, no heap, no argv.
 *
 * Build (model260k.h and tok512.h must sit next to this file):
 *   nios2-elf-gcc -O2 -mcustom-fpu-cfg=60-2 run_baremetal.c -o llama.elf -lm
 *   (drop -mcustom-fpu-cfg if it errors; soft float still works, just slower)
 *
 * Host verification (must print identically to upstream run.c):
 *   cc -O2 -Iembed src/run_baremetal.c -o run_baremetal -lm && ./run_baremetal
 */
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <stdint.h>

/* ------------------------------------------------------------------ blobs --
 * No filesystem, so the weights have to arrive inside the executable. Two ways,
 * and the default is the safe one:
 *
 *   default              -- model260k.h / tok512.h, C arrays declared
 *                           __attribute__((aligned(8))). No .bin files, no
 *                           objcopy, and the float* cast below is legal by
 *                           construction. Same arrays the host build verifies.
 *
 *   -DBLOBS_FROM_OBJCOPY -- link stories260K.bin / tok512.bin as objects.
 *                           objcopy names the symbol after the path you hand it,
 *                           so only a bare filename produces the names below,
 *                           and it promises NOTHING about alignment. Nios II
 *                           masks the low bits of an unaligned word load instead
 *                           of trapping, so a misaligned blob reads as
 *                           plausible-but-wrong weights -- a wrong story, not a
 *                           crash. Fallback only.
 *
 * -DHOST_TEST still selects the embedded path; it is left working because the
 * host verification command above and older notes use it.
 */
#ifdef BLOBS_FROM_OBJCOPY
  extern const unsigned char _binary_stories260K_bin_start[];
  extern const unsigned char _binary_tok512_bin_start[];
  #define MODEL_BLOB  (_binary_stories260K_bin_start)
  #define TOKEN_BLOB  (_binary_tok512_bin_start)
#else
  #include "model260k.h"   /* model260k[],  model260k_len  -- aligned(8) */
  #include "tok512.h"      /* tok512[],     tok512_len                   */
  #define MODEL_BLOB  ((const unsigned char*)model260k)
  #define TOKEN_BLOB  ((const unsigned char*)tok512)
#endif

/* ------------------------------------------------------------------ arena --
 * A bump allocator over a static buffer. The tokenizer wants ~20 KB in many
 * small pieces; relying on a bare-metal heap being configured correctly is an
 * avoidable way to lose an hour to a silent hang.
 */
#define ARENA_BYTES (96 * 1024)
static unsigned char arena[ARENA_BYTES];
static size_t arena_used = 0;

static void* amalloc(size_t n) {
    n = (n + 7u) & ~(size_t)7u;                 /* keep float* casts aligned */
    if (arena_used + n > ARENA_BYTES) {
        fputs("arena exhausted\\n", stderr);
        exit(1);
    }
    void* p = &arena[arena_used];
    arena_used += n;
    return p;
}
'''

# --------------------------------------------------------------------------- 2
READ_CHECKPOINT = '''void read_checkpoint(char* checkpoint, Config* config, TransformerWeights* weights,
                     int* fd, float** data, ssize_t* file_size) {
    /* BARE METAL: no fopen, no fseek, no mmap. The checkpoint is linked into
     * the binary, so "loading" is just pointing at it. Layout is unchanged:
     * a 7-int header followed by the weights. */
    const unsigned char* blob = MODEL_BLOB;
    memcpy(config, blob, sizeof(Config));
    int shared_weights = config->vocab_size > 0 ? 1 : 0;
    config->vocab_size = abs(config->vocab_size);
    *fd = -1;
    *file_size = 0;
    *data = (float*)(void*)blob;
    float* weights_ptr = *data + sizeof(Config)/sizeof(float);
    memory_map_weights(weights, config, weights_ptr, shared_weights);
}

'''

# --------------------------------------------------------------------------- 3
MALLOC_STATE = '''/* Static RunState. Sized for stories260K:
 *   dim 64 | hidden 172 | layers 5 | heads 8 | kv_heads 4 | vocab 512 | seq 512
 * kv_dim = dim * n_kv_heads / n_heads = 32
 * Total ~676 KB -- far too large for the 64 KB on-chip RAM, so the linker MUST
 * place .bss in SDRAM. Getting that wrong hangs with no error message.
 */
#define M_DIM      64
#define M_HIDDEN  172
#define M_LAYERS    5
#define M_HEADS     8
#define M_KVDIM    32
#define M_VOCAB   512
#define M_SEQ     512

static float st_x  [M_DIM];
static float st_xb [M_DIM];
static float st_xb2[M_DIM];
static float st_hb [M_HIDDEN];
static float st_hb2[M_HIDDEN];
static float st_q  [M_DIM];
static float st_key_cache  [M_LAYERS * M_SEQ * M_KVDIM];
static float st_value_cache[M_LAYERS * M_SEQ * M_KVDIM];
static float st_att        [M_HEADS  * M_SEQ];
static float st_logits     [M_VOCAB];

void malloc_run_state(RunState* s, Config* p) {
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    /* Refuse to run rather than silently corrupt memory if the linked
     * checkpoint is not the one these arrays were sized for. */
    if (p->dim != M_DIM || p->hidden_dim != M_HIDDEN || p->n_layers != M_LAYERS
     || p->n_heads != M_HEADS || kv_dim != M_KVDIM || p->vocab_size != M_VOCAB
     || p->seq_len != M_SEQ) {
        fputs("checkpoint does not match compiled-in static sizes\\n", stderr);
        exit(1);
    }
    memset(st_key_cache,   0, sizeof(st_key_cache));
    memset(st_value_cache, 0, sizeof(st_value_cache));
    s->x = st_x;   s->xb = st_xb;  s->xb2 = st_xb2;
    s->hb = st_hb; s->hb2 = st_hb2; s->q = st_q;
    s->key_cache = st_key_cache;
    s->value_cache = st_value_cache;
    s->att = st_att;
    s->logits = st_logits;
}

void free_run_state(RunState* s) { (void)s; }

'''

# --------------------------------------------------------------------------- 5
TIME_STUB = '''long time_in_ms() {
    /* No clock_gettime on bare metal. Returns 0 so the tok/s line is skipped;
     * Justin measures wall-clock with a stopwatch, which is the honest number
     * to put on a slide anyway. */
    return 0;
}

'''


def main() -> None:
    src = get_run_c()
    original_len = len(src)

    # 1. includes
    src = cut(src, "#include <stdio.h>", HEADERS, "// -------------------------")

    # 2. checkpoint loading
    src = cut(src, "void read_checkpoint(", READ_CHECKPOINT, "void build_transformer(")

    # 3. state allocation (replaces both malloc_run_state and free_run_state)
    src = cut(src, "void malloc_run_state(", MALLOC_STATE, "void memory_map_weights(")

    # 4. free_transformer must not munmap something that was never mapped
    src = cut(src, "void free_transformer(", "void free_transformer(Transformer* t) { (void)t; }\n\n",
              "// -------------------------")

    # 5. timing
    src = cut(src, "long time_in_ms()", TIME_STUB, "// -------------------------")

    # 6. tokenizer: blob + arena instead of fopen + malloc
    i = src.index("void build_tokenizer(")
    j = src.index("void free_tokenizer(")
    tok = src[i:j]
    tok = tok.replace("(char**)malloc(vocab_size * sizeof(char*))", "(char**)amalloc(vocab_size * sizeof(char*))")
    tok = tok.replace("(float*)malloc(vocab_size * sizeof(float))", "(float*)amalloc(vocab_size * sizeof(float))")
    tok = tok.replace('    // read in the file\n', '    /* BARE METAL: walk the linked blob instead of fread-ing a file. */\n    const unsigned char* tb = TOKEN_BLOB;\n    size_t off = 0;\n')
    tok = re.sub(r'    FILE \*file = fopen\(tokenizer_path, "rb"\);\n', '', tok)
    tok = re.sub(r'    if \(!file\) \{[^\n]*\n', '', tok)
    tok = tok.replace(
        '    if (fread(&t->max_token_length, sizeof(int), 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE); }',
        '    memcpy(&t->max_token_length, tb + off, sizeof(int)); off += sizeof(int);')
    tok = tok.replace(
        '        if (fread(t->vocab_scores + i, sizeof(float), 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE);}',
        '        memcpy(t->vocab_scores + i, tb + off, sizeof(float)); off += sizeof(float);')
    tok = tok.replace(
        '        if (fread(&len, sizeof(int), 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE); }',
        '        memcpy(&len, tb + off, sizeof(int)); off += sizeof(int);')
    tok = tok.replace('        t->vocab[i] = (char *)malloc(len + 1);', '        t->vocab[i] = (char *)amalloc(len + 1);')
    tok = tok.replace(
        '        if (fread(t->vocab[i], len, 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE); }',
        '        memcpy(t->vocab[i], tb + off, len); off += len;')
    tok = re.sub(r'    fclose\(file\);\n', '', tok)
    src = src[:i] + tok + src[j:]

    # free_tokenizer frees arena pointers -> no-op
    src = cut(src, "void free_tokenizer(", "void free_tokenizer(Tokenizer* t) { (void)t; }\n\n", "char* decode(")

    # sorted_vocab is malloc'd lazily inside encode()
    src = src.replace("t->sorted_vocab = malloc(t->vocab_size * sizeof(TokenIndex));",
                      "t->sorted_vocab = amalloc(t->vocab_size * sizeof(TokenIndex));")
    # sampler probindex buffer
    src = src.replace("sampler->probindex = malloc(sampler->vocab_size * sizeof(ProbIndex));",
                      "sampler->probindex = amalloc(sampler->vocab_size * sizeof(ProbIndex));")
    src = src.replace("void free_sampler(Sampler* sampler) {\n    free(sampler->probindex);\n}",
                      "void free_sampler(Sampler* sampler) { (void)sampler; }")
    # encode() allocates a scratch buffer
    src = src.replace("char* str_buffer = malloc((t->max_token_length*2 +1 +2) * sizeof(char));",
                      "char* str_buffer = amalloc((t->max_token_length*2 +1 +2) * sizeof(char));")
    src = src.replace("    free(str_buffer);\n", "")

    # 7. %f in the tok/s report pulls newlib's float printf into the image
    # NOTE: lambda replacement -- re.sub processes backslashes in a plain
    # replacement string, which would turn our \\n into a real newline and
    # produce an unterminated C string literal.
    src = re.sub(
        r'\s*fprintf\(stderr, "achieved tok/s: %f\\n"[^;]*;',
        lambda m: ('\n        long ms = end - start;\n'
                   '        if (ms > 0) fprintf(stderr, "achieved tok/s: %ld (x100)\\n",'
                   ' (long)(pos-1)*100000L/ms);'),
        src)

    # generate() and chat() still malloc their token buffers
    src = src.replace("int* prompt_tokens = (int*)malloc((strlen(prompt)+3) * sizeof(int));",
                      "int* prompt_tokens = (int*)amalloc((strlen(prompt)+3) * sizeof(int));")
    src = src.replace("int* prompt_tokens = (int*)malloc(1152 * sizeof(int));",
                      "int* prompt_tokens = (int*)amalloc(1152 * sizeof(int));")
    src = src.replace("    free(prompt_tokens);\n", "")

    # 8. main(): no argv, fixed seed, unbuffered so tokens stream as they appear
    i = src.index("int main(int argc, char *argv[]) {")
    src = src[:i] + '''int main(void) {
    /* BARE METAL: no argv. Everything is fixed at compile time.
     * Unbuffered stdout is not cosmetic -- without it newlib buffers the whole
     * generation and the board looks dead for 30 seconds, then dumps at once. */
    setvbuf(stdout, NULL, _IONBF, 0);

    char* checkpoint_path = NULL;
    char* tokenizer_path  = NULL;
    float temperature = 1.0f;
    float topp        = 0.9f;
    int   steps       = 256;
    char* prompt      = NULL;
    unsigned long long rng_seed = 42;   /* fixed: reproducible on stage */
    char* mode        = "generate";
    char* system_prompt = NULL;

    Transformer transformer;
    build_transformer(&transformer, checkpoint_path);
    if (steps == 0 || steps > transformer.config.seq_len) steps = transformer.config.seq_len;

    Tokenizer tokenizer;
    build_tokenizer(&tokenizer, tokenizer_path, transformer.config.vocab_size);

    Sampler sampler;
    build_sampler(&sampler, transformer.config.vocab_size, temperature, topp, rng_seed);

    generate(&transformer, &tokenizer, &sampler, prompt, steps);

    free_sampler(&sampler);
    free_tokenizer(&tokenizer);
    free_transformer(&transformer);
    return 0;
}
#endif
'''
    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "run_baremetal.c")
    open(out, "w", encoding="utf-8").write(src)

    banned = ["fopen(", "mmap(", "munmap(", "open(checkpoint", "sys/mman.h",
              "unistd.h", "fcntl.h", "%f", "= malloc(", ")malloc(", "calloc("]
    hits = [b for b in banned if b in src]
    print(f"  wrote {out}  ({original_len} -> {len(src)} bytes)")
    print(f"  malloc/calloc remaining: {src.count('malloc(') + src.count('calloc(')}")
    print(f"  banned constructs still present: {hits if hits else 'none'}")
    if hits:
        sys.exit(1)


if __name__ == "__main__":
    main()
