#!/usr/bin/env python3
"""Generate run_baremetal.c from Karpathy's run.c by surgical replacement.

Why a generator instead of a hand-written port: we want to be able to say on
stage that the *math is unmodified*. Every transformer function -- rmsnorm,
softmax, matmul, RoPE, attention, the sampler -- is carried across byte for
byte. Only the I/O and allocation boundary is replaced, and this script is the
auditable record of exactly what changed.

What changes, and why:

  1. POSIX includes (fcntl/unistd/sys/mman) -- the board has no OS.
  2. read_checkpoint()  -- there is no filesystem; weights come from a linked blob.
  3. build_tokenizer()  -- same, plus a bump allocator instead of malloc.
  4. malloc_run_state() -- static arrays. 676 KB, sized for stories260K.
  5. time_in_ms()       -- no clock_gettime on bare metal.
  6. main()             -- no argv; fixed seed; unbuffered stdout.
  7. The tok/s line     -- upstream prints it with %f, and newlib's float printf
                           pulls in an enormous amount of code. Integer math.

    python3 tools/make_baremetal.py            # writes src/run_baremetal.c
    python3 tools/make_baremetal.py --q8       # writes src/run_baremetal_q8.c

--q8 additionally replaces TransformerWeights, memory_map_weights, matmul, and
forward()'s weight-touching lines with an int8-weight version (see
tools/embed_model.py --q8 for the blob format). This is the one place the
"math is unmodified" claim above does not hold for the q8 build -- matmul does
int8 dot products against per-row fp32 scales instead of fp32 multiply-add,
and that is the entire point (see docs/HARDWARE-RESULTS.md: the board is
bandwidth-bound, not compute-bound). Every other function -- rmsnorm, softmax,
RoPE, attention, the sampler -- is still carried across byte for byte, exactly
as in the fp32 build. run_baremetal.c (fp32) is untouched by --q8 and stays
independently buildable.
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(ROOT, "vendor")
OUT_DIR = os.path.join(ROOT, "src")
RUN_C_URL = "https://raw.githubusercontent.com/karpathy/llama2.c/master/run.c"


def get_run_c() -> str:
    os.makedirs(VENDOR, exist_ok=True)
    p = os.path.join(VENDOR, "run.c")
    if not os.path.exists(p):
        print("  downloading run.c ...")
        urllib.request.urlretrieve(RUN_C_URL, p)
    return open(p, encoding="utf-8").read()


def cut(src: str, start_marker: str, replacement: str, end_marker: str) -> str:
    """Replace [start_marker .. end_marker) with replacement."""
    i = src.index(start_marker)
    j = src.index(end_marker, i)
    return src[:i] + replacement + src[j:]


# --------------------------------------------------------------------------- 1
HEADERS = '''/* run_baremetal.c -- GENERATED by tools/make_baremetal.py. Do not edit by hand.
 *
 * Karpathy's llama2.c with the operating system removed. Every neural-network
 * function below is byte-for-byte upstream; only I/O and allocation changed.
 *
 * Target: Nios II/f on the Intel FPGA University Program "DE10-Lite Computer".
 * No filesystem, no mmap, no heap, no argv.
 *
 * Build (model260k.h and tok512.h must sit next to this file):
 *   nios2-elf-gcc -O2 -mcustom-fpu-cfg=60-2 run_baremetal.c -o llama.elf -lm
 *   (drop -mcustom-fpu-cfg if it errors; soft float still works, just slower)
 *
 * Host verification (must print identically to upstream run.c):
 *   cc -O2 -Iembed src/run_baremetal.c -o run_baremetal -lm && ./run_baremetal
 */
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <stdint.h>

/* ------------------------------------------------------------------ blobs --
 * No filesystem, so the weights have to arrive inside the executable. Two ways,
 * and the default is the safe one:
 *
 *   default              -- model260k.h / tok512.h, C arrays declared
 *                           __attribute__((aligned(8))). No .bin files, no
 *                           objcopy, and the float* cast below is legal by
 *                           construction. Same arrays the host build verifies.
 *
 *   -DBLOBS_FROM_OBJCOPY -- link stories260K.bin / tok512.bin as objects.
 *                           objcopy names the symbol after the path you hand it,
 *                           so only a bare filename produces the names below,
 *                           and it promises NOTHING about alignment. Nios II
 *                           masks the low bits of an unaligned word load instead
 *                           of trapping, so a misaligned blob reads as
 *                           plausible-but-wrong weights -- a wrong story, not a
 *                           crash. Fallback only.
 *
 * -DHOST_TEST still selects the embedded path; it is left working because the
 * host verification command above and older notes use it.
 */
#ifdef BLOBS_FROM_OBJCOPY
  extern const unsigned char _binary_stories260K_bin_start[];
  extern const unsigned char _binary_tok512_bin_start[];
  #define MODEL_BLOB  (_binary_stories260K_bin_start)
  #define TOKEN_BLOB  (_binary_tok512_bin_start)
#else
  #include "model260k.h"   /* model260k[],  model260k_len  -- aligned(8) */
  #include "tok512.h"      /* tok512[],     tok512_len                   */
  #define MODEL_BLOB  ((const unsigned char*)model260k)
  #define TOKEN_BLOB  ((const unsigned char*)tok512)
#endif

/* ------------------------------------------------------------------ arena --
 * A bump allocator over a static buffer. The tokenizer wants ~20 KB in many
 * small pieces; relying on a bare-metal heap being configured correctly is an
 * avoidable way to lose an hour to a silent hang.
 */
#define ARENA_BYTES (96 * 1024)
static unsigned char arena[ARENA_BYTES];
static size_t arena_used = 0;

static void* amalloc(size_t n) {
    n = (n + 7u) & ~(size_t)7u;                 /* keep float* casts aligned */
    if (arena_used + n > ARENA_BYTES) {
        fputs("arena exhausted\\n", stderr);
        exit(1);
    }
    void* p = &arena[arena_used];
    arena_used += n;
    return p;
}

/* -------------------------------------------------------------------- LEDs --
 * Sign of life. The board is otherwise physically inert while it generates --
 * the story goes out the JTAG UART to a PC, and nothing on the board moves.
 * LEDs sit on an altera_avalon_pio at LEDS_BASE (10 bits, output only).
 *
 * This is a write to a memory-mapped register and nothing else. It does not
 * touch stdout, does not touch any transformer function, and cannot change an
 * output byte. On any non-Nios target it compiles to nothing.
 */
#ifdef __nios2__
  #include "system.h"                 /* LEDS_BASE */
  #include "altera_avalon_pio_regs.h" /* IOWR_ALTERA_AVALON_PIO_DATA */
  static void vs_leds(unsigned v) { IOWR_ALTERA_AVALON_PIO_DATA(LEDS_BASE, v & 0x3ffu); }
#else
  static void vs_leds(unsigned v) { (void)v; }
#endif
'''

# --------------------------------------------------------------------------- 1q8
# int8-weight variant of HEADERS: same blob/arena/LED machinery, only the
# weight header and MODEL_BLOB source differ. tok512.h (tokenizer) is
# unquantized in both builds.
HEADERS_Q8 = '''/* run_baremetal_q8.c -- GENERATED by tools/make_baremetal.py --q8. Do not edit
 * by hand. Regenerate with: python3 tools/make_baremetal.py --q8
 *
 * Karpathy's llama2.c with the operating system removed AND int8 weights.
 * rmsnorm, softmax, RoPE, attention, and the sampler are still byte-for-byte
 * upstream. matmul and the weight layout are NOT upstream -- the board is
 * bandwidth-bound (no data cache, 16-bit SDRAM; see docs/HARDWARE-RESULTS.md),
 * so weights are int8 with one fp32 scale per output row, packed 4-per-word
 * so the Nios core's uncached loads move 4 weights per SDRAM transaction
 * instead of 1. See tools/embed_model.py --q8 for the quantization and blob
 * format. This build is NOT byte-exact against upstream fp32 -- see
 * dist/llama-nios/expected_output_q8.txt for its own golden reference.
 *
 * Target: Nios II/f on the Intel FPGA University Program "DE10-Lite Computer".
 * No filesystem, no mmap, no heap, no argv.
 *
 * Build (model260k_q8.h and tok512.h must sit next to this file):
 *   nios2-elf-gcc -O2 -mcustom-fpu-cfg=60-2 run_baremetal_q8.c -o llama_q8.elf -lm
 *   (drop -mcustom-fpu-cfg if it errors; soft float still works, just slower)
 *
 * Host verification (compare against expected_output_q8.txt, NOT
 * expected_output.txt -- this build is intentionally not fp32-exact):
 *   cc -O2 -Iembed src/run_baremetal_q8.c -o run_baremetal_q8 -lm && ./run_baremetal_q8
 */
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <stdint.h>

#ifdef BLOBS_FROM_OBJCOPY
  extern const unsigned char _binary_stories260K_bin_start[];
  extern const unsigned char _binary_tok512_bin_start[];
  #define MODEL_BLOB  (_binary_stories260K_bin_start)
  #define TOKEN_BLOB  (_binary_tok512_bin_start)
#else
  #include "model260k_q8.h" /* model260k_q8[], model260k_q8_len -- aligned(8) */
  #include "tok512.h"       /* tok512[],       tok512_len       -- unquantized */
  #define MODEL_BLOB  ((const unsigned char*)model260k_q8)
  #define TOKEN_BLOB  ((const unsigned char*)tok512)
#endif

/* ------------------------------------------------------------------ arena --
 * A bump allocator over a static buffer. The tokenizer wants ~20 KB in many
 * small pieces; relying on a bare-metal heap being configured correctly is an
 * avoidable way to lose an hour to a silent hang.
 */
#define ARENA_BYTES (96 * 1024)
static unsigned char arena[ARENA_BYTES];
static size_t arena_used = 0;

static void* amalloc(size_t n) {
    n = (n + 7u) & ~(size_t)7u;                 /* keep float* casts aligned */
    if (arena_used + n > ARENA_BYTES) {
        fputs("arena exhausted\\n", stderr);
        exit(1);
    }
    void* p = &arena[arena_used];
    arena_used += n;
    return p;
}

/* -------------------------------------------------------------------- LEDs --
 * Sign of life. The board is otherwise physically inert while it generates --
 * the story goes out the JTAG UART to a PC, and nothing on the board moves.
 * LEDs sit on an altera_avalon_pio at LEDS_BASE (10 bits, output only).
 *
 * This is a write to a memory-mapped register and nothing else. It does not
 * touch stdout, does not touch any transformer function, and cannot change an
 * output byte. On any non-Nios target it compiles to nothing.
 */
#ifdef __nios2__
  #include "system.h"                 /* LEDS_BASE */
  #include "altera_avalon_pio_regs.h" /* IOWR_ALTERA_AVALON_PIO_DATA */
  static void vs_leds(unsigned v) { IOWR_ALTERA_AVALON_PIO_DATA(LEDS_BASE, v & 0x3ffu); }
#else
  static void vs_leds(unsigned v) { (void)v; }
#endif
'''

# --------------------------------------------------------------------------- 2
READ_CHECKPOINT = '''void read_checkpoint(char* checkpoint, Config* config, TransformerWeights* weights,
                     int* fd, float** data, ssize_t* file_size) {
    /* BARE METAL: no fopen, no fseek, no mmap. The checkpoint is linked into
     * the binary, so "loading" is just pointing at it. Layout is unchanged:
     * a 7-int header followed by the weights. */
    const unsigned char* blob = MODEL_BLOB;
    memcpy(config, blob, sizeof(Config));
    int shared_weights = config->vocab_size > 0 ? 1 : 0;
    config->vocab_size = abs(config->vocab_size);
    *fd = -1;
    *file_size = 0;
    *data = (float*)(void*)blob;
    float* weights_ptr = *data + sizeof(Config)/sizeof(float);
    memory_map_weights(weights, config, weights_ptr, shared_weights);
}

'''

# --------------------------------------------------------------------------- 3
MALLOC_STATE = '''/* Static RunState. Sized for stories260K:
 *   dim 64 | hidden 172 | layers 5 | heads 8 | kv_heads 4 | vocab 512 | seq 512
 * kv_dim = dim * n_kv_heads / n_heads = 32
 * Total ~676 KB -- far too large for the 64 KB on-chip RAM, so the linker MUST
 * place .bss in SDRAM. Getting that wrong hangs with no error message.
 */
#define M_DIM      64
#define M_HIDDEN  172
#define M_LAYERS    5
#define M_HEADS     8
#define M_KVDIM    32
#define M_VOCAB   512
#define M_SEQ     512

static float st_x  [M_DIM];
static float st_xb [M_DIM];
static float st_xb2[M_DIM];
static float st_hb [M_HIDDEN];
static float st_hb2[M_HIDDEN];
static float st_q  [M_DIM];
static float st_key_cache  [M_LAYERS * M_SEQ * M_KVDIM];
static float st_value_cache[M_LAYERS * M_SEQ * M_KVDIM];
static float st_att        [M_HEADS  * M_SEQ];
static float st_logits     [M_VOCAB];

void malloc_run_state(RunState* s, Config* p) {
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    /* Refuse to run rather than silently corrupt memory if the linked
     * checkpoint is not the one these arrays were sized for. */
    if (p->dim != M_DIM || p->hidden_dim != M_HIDDEN || p->n_layers != M_LAYERS
     || p->n_heads != M_HEADS || kv_dim != M_KVDIM || p->vocab_size != M_VOCAB
     || p->seq_len != M_SEQ) {
        fputs("checkpoint does not match compiled-in static sizes\\n", stderr);
        exit(1);
    }
    memset(st_key_cache,   0, sizeof(st_key_cache));
    memset(st_value_cache, 0, sizeof(st_value_cache));
    s->x = st_x;   s->xb = st_xb;  s->xb2 = st_xb2;
    s->hb = st_hb; s->hb2 = st_hb2; s->q = st_q;
    s->key_cache = st_key_cache;
    s->value_cache = st_value_cache;
    s->att = st_att;
    s->logits = st_logits;
}

void free_run_state(RunState* s) { (void)s; }

'''

# --------------------------------------------------------------------------- 5
TIME_STUB = '''long time_in_ms() {
    /* No clock_gettime on bare metal. Returns 0 so the tok/s line is skipped;
     * Justin measures wall-clock with a stopwatch, which is the honest number
     * to put on a slide anyway. */
    return 0;
}

'''

# --------------------------------------------------------------------------- 0q8
# Everything below is only spliced in for --q8. It replaces four upstream
# regions (struct, weight mapping, checkpoint parse, matmul+forward) with an
# int8-weight equivalent; every other upstream function is untouched.

Q8_MAGIC = "0x51385653u"  # must match tools/embed_model.py's Q8_MAGIC exactly

TRANSFORMER_WEIGHTS_Q8 = '''typedef struct {
    // token embedding table -- int8 rows + one fp32 scale per row (vocab, dim).
    // Also IS the classifier: stories260K has shared_weights=1, so wcls/
    // wcls_scale below just alias these two pointers (see memory_map_weights).
    int8_t* token_embedding_table;
    float*  token_embedding_scale;
    // weights for rmsnorms -- kept fp32, same choice upstream runq.c makes:
    // these are cheap (704 floats total) and softmax/rmsnorm stability is not
    // where the bandwidth problem is.
    float* rms_att_weight; // (layer, dim) rmsnorm weights
    float* rms_ffn_weight; // (layer, dim)
    // weights for matmuls: int8 (layer*d, n) rows + one fp32 scale per row,
    // packed 4-per-32-bit-word (see matmul below). note dim == n_heads * head_size
    int8_t* wq; float* wq_scale; // (layer*dim, dim)
    int8_t* wk; float* wk_scale; // (layer*kv_dim, dim)
    int8_t* wv; float* wv_scale; // (layer*kv_dim, dim)
    int8_t* wo; float* wo_scale; // (layer*dim, dim)
    // weights for ffn
    int8_t* w1; float* w1_scale; // (layer*hidden_dim, dim)
    int8_t* w2; float* w2_scale; // (layer*dim, hidden_dim)
    int8_t* w3; float* w3_scale; // (layer*hidden_dim, dim)
    // final rmsnorm
    float* rms_final_weight; // (dim,)
    // (optional) classifier weights for the logits -- shared with the token
    // embedding table above for stories260K; see memory_map_weights.
    int8_t* wcls; float* wcls_scale;
} TransformerWeights;
'''

READ_CHECKPOINT_Q8 = f'''void read_checkpoint(char* checkpoint, Config* config, TransformerWeights* weights,
                     int* fd, float** data, ssize_t* file_size) {{
    /* BARE METAL, int8 weights: no fopen, no fseek, no mmap. Layout written by
     * tools/embed_model.py --q8: 7-int Config header, then a magic uint32,
     * then the quantized tensors in memory_map_weights order below. */
    const unsigned char* blob = MODEL_BLOB;
    memcpy(config, blob, sizeof(Config));
    int shared_weights = config->vocab_size > 0 ? 1 : 0;
    config->vocab_size = abs(config->vocab_size);
    *fd = -1;
    *file_size = 0;
    *data = (float*)(void*)blob;

    uint32_t magic;
    memcpy(&magic, blob + sizeof(Config), sizeof(magic));
    if (magic != {Q8_MAGIC}) {{
        /* Refuse to run rather than silently misread a stale/mismatched blob --
         * same philosophy as malloc_run_state's size guard below. */
        fputs("q8 blob magic mismatch -- stale or wrong model260k_q8.h\\n", stderr);
        exit(1);
    }}
    unsigned char* weights_ptr = (unsigned char*)blob + sizeof(Config) + sizeof(magic);
    memory_map_weights(weights, config, weights_ptr, shared_weights);
}}

'''

MALLOC_STATE_Q8 = '''/* Static RunState. Sized for stories260K:
 *   dim 64 | hidden 172 | layers 5 | heads 8 | kv_heads 4 | vocab 512 | seq 512
 * kv_dim = dim * n_kv_heads / n_heads = 32
 * Total ~676 KB -- far too large for the 64 KB on-chip RAM, so the linker MUST
 * place .bss in SDRAM. Getting that wrong hangs with no error message.
 */
#define M_DIM      64
#define M_HIDDEN  172
#define M_LAYERS    5
#define M_HEADS     8
#define M_KVDIM    32
#define M_VOCAB   512
#define M_SEQ     512

static float st_x  [M_DIM];
static float st_xb [M_DIM];
static float st_xb2[M_DIM];
static float st_hb [M_HIDDEN];
static float st_hb2[M_HIDDEN];
static float st_q  [M_DIM];
static float st_key_cache  [M_LAYERS * M_SEQ * M_KVDIM];
static float st_value_cache[M_LAYERS * M_SEQ * M_KVDIM];
static float st_att        [M_HEADS  * M_SEQ];
static float st_logits     [M_VOCAB];

/* Runtime-quantized activation scratch for matmul (see matmul below). Sized
 * to the largest n across all 8 call sites in forward() (172, for w2).
 * aligned(4) is load-bearing: matmul reads it 4 bytes at a time via
 * uint32_t*, and Nios II masks the low address bits of an unaligned word
 * load instead of trapping -- a misaligned buffer would read as
 * plausible-but-wrong numbers, not a crash (the same failure mode the
 * objcopy blob path warns about elsewhere in this project).
 */
static int8_t st_xq[M_HIDDEN] __attribute__((aligned(4)));

void malloc_run_state(RunState* s, Config* p) {
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    /* Refuse to run rather than silently corrupt memory if the linked
     * checkpoint is not the one these arrays were sized for. */
    if (p->dim != M_DIM || p->hidden_dim != M_HIDDEN || p->n_layers != M_LAYERS
     || p->n_heads != M_HEADS || kv_dim != M_KVDIM || p->vocab_size != M_VOCAB
     || p->seq_len != M_SEQ) {
        fputs("checkpoint does not match compiled-in static sizes\\n", stderr);
        exit(1);
    }
    memset(st_key_cache,   0, sizeof(st_key_cache));
    memset(st_value_cache, 0, sizeof(st_value_cache));
    s->x = st_x;   s->xb = st_xb;  s->xb2 = st_xb2;
    s->hb = st_hb; s->hb2 = st_hb2; s->q = st_q;
    s->key_cache = st_key_cache;
    s->value_cache = st_value_cache;
    s->att = st_att;
    s->logits = st_logits;
}

void free_run_state(RunState* s) { (void)s; }

/* int8-weight memory map. Walks the blob in exactly the order
 * tools/embed_model.py --q8's quantize() wrote it, mirroring upstream
 * memory_map_weights()'s tensor order but stepping in bytes: each quantized
 * tensor is `rows` int8 columns of `cols` values, immediately followed by
 * `rows` fp32 scales (cols is always a multiple of 4, so this boundary and
 * every subsequent one stays 4-byte aligned with no padding needed). rmsnorm
 * tensors pass through as plain fp32, same as upstream runq.c.
 */
void memory_map_weights(TransformerWeights *w, Config* p, unsigned char* ptr, int shared_weights) {
    int head_size = p->dim / p->n_heads;
    unsigned long long L = p->n_layers;
    int dim = p->dim, hd = p->hidden_dim;
    int kv_dim = p->n_kv_heads * head_size;
    long V = p->vocab_size;
    long r;

    if (!shared_weights) {
        /* Not exercised by stories260K (vocab_size > 0 in its checkpoint) and
         * not implemented in the Python quantizer either -- fail loudly
         * rather than read garbage if this is ever pointed at a different
         * checkpoint. */
        fputs("q8 build only supports a shared classifier (stories260K)\\n", stderr);
        exit(1);
    }

    r = V;
    w->token_embedding_table = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->token_embedding_scale = (float*)ptr;  ptr += (size_t)r * sizeof(float);

    w->rms_att_weight = (float*)ptr; ptr += (size_t)L * dim * sizeof(float);

    r = (long)L * dim;
    w->wq = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wq_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * kv_dim;
    w->wk = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wk_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * kv_dim;
    w->wv = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wv_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * dim;
    w->wo = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wo_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    w->rms_ffn_weight = (float*)ptr; ptr += (size_t)L * dim * sizeof(float);

    r = (long)L * hd;
    w->w1 = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->w1_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * dim;
    w->w2 = (int8_t*)ptr; ptr += (size_t)r * hd;
    w->w2_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * hd;
    w->w3 = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->w3_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    w->rms_final_weight = (float*)ptr; ptr += (size_t)dim * sizeof(float);

    w->wcls = w->token_embedding_table;
    w->wcls_scale = w->token_embedding_scale;
}

'''

MATMUL_FORWARD_Q8 = '''void matmul(float* xout, float* x, int8_t* w, float* wscale, int n, int d) {
    // int8 W (d,n) @ x (n,) -> xout (d,), one fp32 scale per row of W.
    // Not upstream -- see docs/HARDWARE-RESULTS.md: this board is
    // bandwidth-bound (no data cache, 16-bit SDRAM), so every uncached load
    // here is packed 4 values to a 32-bit word instead of 1. n is always a
    // multiple of 4 (64 or 172 for stories260K; asserted in the Python
    // quantizer), so there is no tail case to handle.
    //
    // x is quantized into st_xq once per call, O(n) against the O(n*d) cost
    // of the loop below -- see MALLOC_STATE_Q8 for why st_xq must stay
    // 4-byte aligned.
    float xmax = 0.0f;
    for (int j = 0; j < n; j++) {
        float a = fabsf(x[j]);
        if (a > xmax) xmax = a;
    }
    float xs = (xmax > 0.0f) ? (xmax / 127.0f) : 1.0f;
    for (int j = 0; j < n; j++) {
        int q = (int)roundf(x[j] / xs);
        q = q > 127 ? 127 : (q < -127 ? -127 : q);
        st_xq[j] = (int8_t)q;
    }

    int i;
    #pragma omp parallel for private(i)
    for (i = 0; i < d; i++) {
        const uint32_t* wp = (const uint32_t*)(w + (size_t)i * n);
        const uint32_t* xp = (const uint32_t*)st_xq;
        int32_t ival = 0;
        for (int j = 0; j < n >> 2; j++) {
            uint32_t wpk = wp[j];
            uint32_t xpk = xp[j];
            ival += (int32_t)(int8_t)( wpk        & 0xff) * (int32_t)(int8_t)( xpk        & 0xff);
            ival += (int32_t)(int8_t)((wpk >>  8) & 0xff) * (int32_t)(int8_t)((xpk >>  8) & 0xff);
            ival += (int32_t)(int8_t)((wpk >> 16) & 0xff) * (int32_t)(int8_t)((xpk >> 16) & 0xff);
            ival += (int32_t)(int8_t)((wpk >> 24) & 0xff) * (int32_t)(int8_t)((xpk >> 24) & 0xff);
        }
        xout[i] = (float)ival * wscale[i] * xs;
    }
}

float* forward(Transformer* transformer, int token, int pos) {

    // a few convenience variables
    Config* p = &transformer->config;
    TransformerWeights* w = &transformer->weights;
    RunState* s = &transformer->state;
    float *x = s->x;
    int dim = p->dim;
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int kv_mul = p->n_heads / p->n_kv_heads; // integer multiplier of the kv sharing in multiquery
    int hidden_dim =  p->hidden_dim;
    int head_size = dim / p->n_heads;

    // copy the token embedding into x -- dequantized, since x is fp32
    // everywhere downstream (RoPE/attention/softmax are all still upstream
    // fp32 math; only matmul's inputs are int8).
    {
        int8_t* content_row = w->token_embedding_table + (size_t)token * dim;
        float   row_scale    = w->token_embedding_scale[token];
        for (int j = 0; j < dim; j++) x[j] = content_row[j] * row_scale;
    }

    // forward all the layers
    for(unsigned long long l = 0; l < p->n_layers; l++) {

        // attention rmsnorm
        rmsnorm(s->xb, x, w->rms_att_weight + l*dim, dim);

        // key and value point to the kv cache
        int loff = l * p->seq_len * kv_dim; // kv cache layer offset for convenience
        s->k = s->key_cache + loff + pos * kv_dim;
        s->v = s->value_cache + loff + pos * kv_dim;

        // qkv matmuls for this position
        matmul(s->q, s->xb, w->wq + l*dim*dim, w->wq_scale + l*dim, dim, dim);
        matmul(s->k, s->xb, w->wk + l*dim*kv_dim, w->wk_scale + l*kv_dim, dim, kv_dim);
        matmul(s->v, s->xb, w->wv + l*dim*kv_dim, w->wv_scale + l*kv_dim, dim, kv_dim);

        // RoPE relative positional encoding: complex-valued rotate q and k in each head
        for (int i = 0; i < dim; i+=2) {
            int head_dim = i % head_size;
            float freq = 1.0f / powf(10000.0f, head_dim / (float)head_size);
            float val = pos * freq;
            float fcr = cosf(val);
            float fci = sinf(val);
            int rotn = i < kv_dim ? 2 : 1; // how many vectors? 2 = q & k, 1 = q only
            for (int v = 0; v < rotn; v++) {
                float* vec = v == 0 ? s->q : s->k; // the vector to rotate (query or key)
                float v0 = vec[i];
                float v1 = vec[i+1];
                vec[i]   = v0 * fcr - v1 * fci;
                vec[i+1] = v0 * fci + v1 * fcr;
            }
        }

        // multihead attention. iterate over all heads
        int h;
        #pragma omp parallel for private(h)
        for (h = 0; h < p->n_heads; h++) {
            // get the query vector for this head
            float* q = s->q + h * head_size;
            // attention scores for this head
            float* att = s->att + h * p->seq_len;
            // iterate over all timesteps, including the current one
            for (int t = 0; t <= pos; t++) {
                // get the key vector for this head and at this timestep
                float* k = s->key_cache + loff + t * kv_dim + (h / kv_mul) * head_size;
                // calculate the attention score as the dot product of q and k
                float score = 0.0f;
                for (int i = 0; i < head_size; i++) {
                    score += q[i] * k[i];
                }
                score /= sqrtf(head_size);
                // save the score to the attention buffer
                att[t] = score;
            }

            // softmax the scores to get attention weights, from 0..pos inclusively
            softmax(att, pos + 1);

            // weighted sum of the values, store back into xb
            float* xb = s->xb + h * head_size;
            memset(xb, 0, head_size * sizeof(float));
            for (int t = 0; t <= pos; t++) {
                // get the value vector for this head and at this timestep
                float* v = s->value_cache + loff + t * kv_dim + (h / kv_mul) * head_size;
                // get the attention weight for this timestep
                float a = att[t];
                // accumulate the weighted value into xb
                for (int i = 0; i < head_size; i++) {
                    xb[i] += a * v[i];
                }
            }
        }

        // final matmul to get the output of the attention
        matmul(s->xb2, s->xb, w->wo + l*dim*dim, w->wo_scale + l*dim, dim, dim);

        // residual connection back into x
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb2[i];
        }

        // ffn rmsnorm
        rmsnorm(s->xb, x, w->rms_ffn_weight + l*dim, dim);

        // Now for FFN in PyTorch we have: self.w2(F.silu(self.w1(x)) * self.w3(x))
        // first calculate self.w1(x) and self.w3(x)
        matmul(s->hb, s->xb, w->w1 + l*dim*hidden_dim, w->w1_scale + l*hidden_dim, dim, hidden_dim);
        matmul(s->hb2, s->xb, w->w3 + l*dim*hidden_dim, w->w3_scale + l*hidden_dim, dim, hidden_dim);

        // SwiGLU non-linearity
        for (int i = 0; i < hidden_dim; i++) {
            float val = s->hb[i];
            // silu(x)=x*σ(x), where σ(x) is the logistic sigmoid
            val *= (1.0f / (1.0f + expf(-val)));
            // elementwise multiply with w3(x)
            val *= s->hb2[i];
            s->hb[i] = val;
        }

        // final matmul to get the output of the ffn
        matmul(s->xb, s->hb, w->w2 + l*dim*hidden_dim, w->w2_scale + l*dim, hidden_dim, dim);

        // residual connection
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb[i];
        }
    }

    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);

    // classifier into logits
    matmul(s->logits, x, w->wcls, w->wcls_scale, p->dim, p->vocab_size);
    return s->logits;
}

'''


def main() -> None:
    q8 = "--q8" in sys.argv[1:]
    src = get_run_c()
    original_len = len(src)

    # 1. includes
    src = cut(src, "#include <stdio.h>", HEADERS_Q8 if q8 else HEADERS, "// -------------------------")

    if q8:
        # 0q8. TransformerWeights: int8 tensor pointers + one fp32 scale per
        # output row, instead of plain float*. Precedes malloc_run_state in
        # upstream source, so this is an independent cut from #3 below.
        src = cut(src, "typedef struct {\n    // token embedding table",
                  TRANSFORMER_WEIGHTS_Q8, "typedef struct {\n    // current wave of activations")

    # 2. checkpoint loading
    src = cut(src, "void read_checkpoint(", READ_CHECKPOINT_Q8 if q8 else READ_CHECKPOINT,
              "void build_transformer(")

    # 3. state allocation (replaces both malloc_run_state and free_run_state).
    # --q8 widens the end marker to also absorb and replace memory_map_weights
    # (upstream's float-pointer version can't walk an int8+scale blob).
    src = cut(src, "void malloc_run_state(", MALLOC_STATE_Q8 if q8 else MALLOC_STATE,
              "void read_checkpoint(" if q8 else "void memory_map_weights(")

    if q8:
        # 3b-q8. matmul + forward(): matmul becomes an int8 dot product against
        # per-row fp32 scales (see MATMUL_FORWARD_Q8 for why -- this is the one
        # place the generator's "math is unmodified" guarantee does not hold).
        # forward()'s control flow, RoPE, attention, and softmax are unchanged;
        # only the embedding lookup and the 8 matmul call sites differ, to
        # thread each weight tensor's scale array through.
        src = cut(src, "void matmul(", MATMUL_FORWARD_Q8,
                  "// The Byte Pair Encoding (BPE) Tokenizer that translates strings <-> tokens")

    # 4. free_transformer must not munmap something that was never mapped
    src = cut(src, "void free_transformer(", "void free_transformer(Transformer* t) { (void)t; }\n\n",
              "// -------------------------")

    # 5. timing
    src = cut(src, "long time_in_ms()", TIME_STUB, "// -------------------------")

    # 6. tokenizer: blob + arena instead of fopen + malloc
    i = src.index("void build_tokenizer(")
    j = src.index("void free_tokenizer(")
    tok = src[i:j]
    tok = tok.replace("(char**)malloc(vocab_size * sizeof(char*))", "(char**)amalloc(vocab_size * sizeof(char*))")
    tok = tok.replace("(float*)malloc(vocab_size * sizeof(float))", "(float*)amalloc(vocab_size * sizeof(float))")
    tok = tok.replace('    // read in the file\n', '    /* BARE METAL: walk the linked blob instead of fread-ing a file. */\n    const unsigned char* tb = TOKEN_BLOB;\n    size_t off = 0;\n')
    tok = re.sub(r'    FILE \*file = fopen\(tokenizer_path, "rb"\);\n', '', tok)
    tok = re.sub(r'    if \(!file\) \{[^\n]*\n', '', tok)
    tok = tok.replace(
        '    if (fread(&t->max_token_length, sizeof(int), 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE); }',
        '    memcpy(&t->max_token_length, tb + off, sizeof(int)); off += sizeof(int);')
    tok = tok.replace(
        '        if (fread(t->vocab_scores + i, sizeof(float), 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE);}',
        '        memcpy(t->vocab_scores + i, tb + off, sizeof(float)); off += sizeof(float);')
    tok = tok.replace(
        '        if (fread(&len, sizeof(int), 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE); }',
        '        memcpy(&len, tb + off, sizeof(int)); off += sizeof(int);')
    tok = tok.replace('        t->vocab[i] = (char *)malloc(len + 1);', '        t->vocab[i] = (char *)amalloc(len + 1);')
    tok = tok.replace(
        '        if (fread(t->vocab[i], len, 1, file) != 1) { fprintf(stderr, "failed read\\n"); exit(EXIT_FAILURE); }',
        '        memcpy(t->vocab[i], tb + off, len); off += len;')
    tok = re.sub(r'    fclose\(file\);\n', '', tok)
    src = src[:i] + tok + src[j:]

    # free_tokenizer frees arena pointers -> no-op
    src = cut(src, "void free_tokenizer(", "void free_tokenizer(Tokenizer* t) { (void)t; }\n\n", "char* decode(")

    # sorted_vocab is malloc'd lazily inside encode()
    src = src.replace("t->sorted_vocab = malloc(t->vocab_size * sizeof(TokenIndex));",
                      "t->sorted_vocab = amalloc(t->vocab_size * sizeof(TokenIndex));")
    # sampler probindex buffer
    src = src.replace("sampler->probindex = malloc(sampler->vocab_size * sizeof(ProbIndex));",
                      "sampler->probindex = amalloc(sampler->vocab_size * sizeof(ProbIndex));")
    src = src.replace("void free_sampler(Sampler* sampler) {\n    free(sampler->probindex);\n}",
                      "void free_sampler(Sampler* sampler) { (void)sampler; }")
    # encode() allocates a scratch buffer
    src = src.replace("char* str_buffer = malloc((t->max_token_length*2 +1 +2) * sizeof(char));",
                      "char* str_buffer = amalloc((t->max_token_length*2 +1 +2) * sizeof(char));")
    src = src.replace("    free(str_buffer);\n", "")

    # 7. %f in the tok/s report pulls newlib's float printf into the image
    # NOTE: lambda replacement -- re.sub processes backslashes in a plain
    # replacement string, which would turn our \\n into a real newline and
    # produce an unterminated C string literal.
    src = re.sub(
        r'\s*fprintf\(stderr, "achieved tok/s: %f\\n"[^;]*;',
        lambda m: ('\n        long ms = end - start;\n'
                   '        if (ms > 0) fprintf(stderr, "achieved tok/s: %ld (x100)\\n",'
                   ' (long)(pos-1)*100000L/ms);'),
        src)

    # 7b. LEDs: one write per token, so the board shows it is alive. The site is
    # unique -- chat() has the same three lines at 12-space indent, not 8.
    LED_SITE = ('        safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes\n'
                '        fflush(stdout);\n'
                '        token = next;\n')
    assert src.count(LED_SITE) == 1, "generate() LED hook site not unique"
    src = src.replace(LED_SITE,
        '        safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes\n'
        '        fflush(stdout);\n'
        '        vs_leds(pos);  /* SIGN OF LIFE: token counter in binary on LEDR[9:0] */\n'
        '        token = next;\n')

    # generate() and chat() still malloc their token buffers
    src = src.replace("int* prompt_tokens = (int*)malloc((strlen(prompt)+3) * sizeof(int));",
                      "int* prompt_tokens = (int*)amalloc((strlen(prompt)+3) * sizeof(int));")
    src = src.replace("int* prompt_tokens = (int*)malloc(1152 * sizeof(int));",
                      "int* prompt_tokens = (int*)amalloc(1152 * sizeof(int));")
    src = src.replace("    free(prompt_tokens);\n", "")

    # 8. main(): no argv, fixed seed, unbuffered so tokens stream as they appear
    i = src.index("int main(int argc, char *argv[]) {")
    src = src[:i] + '''int main(void) {
    /* BARE METAL: no argv. Everything is fixed at compile time.
     * Unbuffered stdout is not cosmetic -- without it newlib buffers the whole
     * generation and the board looks dead for 30 seconds, then dumps at once. */
    setvbuf(stdout, NULL, _IONBF, 0);
    vs_leds(0x3ff);   /* all on while the tokenizer builds -- the board is not dead */

    char* checkpoint_path = NULL;
    char* tokenizer_path  = NULL;
    float temperature = 1.0f;
    float topp        = 0.9f;
    int   steps       = 256;
    char* prompt      = NULL;
    unsigned long long rng_seed = 42;   /* fixed: reproducible on stage */
    char* mode        = "generate";
    char* system_prompt = NULL;

    Transformer transformer;
    build_transformer(&transformer, checkpoint_path);
    if (steps == 0 || steps > transformer.config.seq_len) steps = transformer.config.seq_len;

    Tokenizer tokenizer;
    build_tokenizer(&tokenizer, tokenizer_path, transformer.config.vocab_size);

    Sampler sampler;
    build_sampler(&sampler, transformer.config.vocab_size, temperature, topp, rng_seed);

    generate(&transformer, &tokenizer, &sampler, prompt, steps);
    vs_leds(0x3ff);   /* all on, held: generation finished cleanly */

    free_sampler(&sampler);
    free_tokenizer(&tokenizer);
    free_transformer(&transformer);
    return 0;
}
#endif
'''
    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "run_baremetal_q8.c" if q8 else "run_baremetal.c")
    open(out, "w", encoding="utf-8").write(src)

    banned = ["fopen(", "mmap(", "munmap(", "open(checkpoint", "sys/mman.h",
              "unistd.h", "fcntl.h", "%f", "= malloc(", ")malloc(", "calloc("]
    hits = [b for b in banned if b in src]
    print(f"  wrote {out}  ({original_len} -> {len(src)} bytes)")
    print(f"  malloc/calloc remaining: {src.count('malloc(') + src.count('calloc(')}")
    print(f"  banned constructs still present: {hits if hits else 'none'}")
    if hits:
        sys.exit(1)


if __name__ == "__main__":
    main()
