/* Inference for Llama-2 Transformer model in pure C */

/* run_baremetal_q8.c -- GENERATED by tools/make_baremetal.py --q8. Do not edit
 * by hand. Regenerate with: python3 tools/make_baremetal.py --q8
 *
 * Karpathy's llama2.c with the operating system removed AND int8 weights.
 * rmsnorm, softmax, RoPE, attention, and the sampler are still byte-for-byte
 * upstream. matmul and the weight layout are NOT upstream -- the board is
 * bandwidth-bound (no data cache, 16-bit SDRAM; see docs/HARDWARE-RESULTS.md),
 * so weights are int8 with one fp32 scale per output row, packed 4-per-word
 * so the Nios core's uncached loads move 4 weights per SDRAM transaction
 * instead of 1. See tools/embed_model.py --q8 for the quantization and blob
 * format. This build is NOT byte-exact against upstream fp32 -- see
 * dist/llama-nios/expected_output_q8.txt for its own golden reference.
 *
 * Target: Nios II/f on the Intel FPGA University Program "DE10-Lite Computer".
 * No filesystem, no mmap, no heap, no argv.
 *
 * Build (model260k_q8.h and tok512.h must sit next to this file):
 *   nios2-elf-gcc -O2 -mcustom-fpu-cfg=60-2 run_baremetal_q8.c -o llama_q8.elf -lm
 *   (drop -mcustom-fpu-cfg if it errors; soft float still works, just slower)
 *
 * Host verification (compare against expected_output_q8.txt, NOT
 * expected_output.txt -- this build is intentionally not fp32-exact):
 *   cc -O2 -Iembed src/run_baremetal_q8.c -o run_baremetal_q8 -lm && ./run_baremetal_q8
 */
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include <string.h>
#include <stdint.h>

#ifdef BLOBS_FROM_OBJCOPY
  extern const unsigned char _binary_stories260K_bin_start[];
  extern const unsigned char _binary_tok512_bin_start[];
  #define MODEL_BLOB  (_binary_stories260K_bin_start)
  #define TOKEN_BLOB  (_binary_tok512_bin_start)
#else
  #include "model260k_q8.h" /* model260k_q8[], model260k_q8_len -- aligned(8) */
  #include "tok512.h"       /* tok512[],       tok512_len       -- unquantized */
  #define MODEL_BLOB  ((const unsigned char*)model260k_q8)
  #define TOKEN_BLOB  ((const unsigned char*)tok512)
#endif

/* ------------------------------------------------------------------ arena --
 * A bump allocator over a static buffer. The tokenizer wants ~20 KB in many
 * small pieces; relying on a bare-metal heap being configured correctly is an
 * avoidable way to lose an hour to a silent hang.
 */
#define ARENA_BYTES (96 * 1024)
static unsigned char arena[ARENA_BYTES];
static size_t arena_used = 0;

static void* amalloc(size_t n) {
    n = (n + 7u) & ~(size_t)7u;                 /* keep float* casts aligned */
    if (arena_used + n > ARENA_BYTES) {
        fputs("arena exhausted\n", stderr);
        exit(1);
    }
    void* p = &arena[arena_used];
    arena_used += n;
    return p;
}

/* -------------------------------------------------------------------- LEDs --
 * Sign of life. The board is otherwise physically inert while it generates --
 * the story goes out the JTAG UART to a PC, and nothing on the board moves.
 * LEDs sit on an altera_avalon_pio at LEDS_BASE (10 bits, output only).
 *
 * This is a write to a memory-mapped register and nothing else. It does not
 * touch stdout, does not touch any transformer function, and cannot change an
 * output byte. On any non-Nios target it compiles to nothing.
 */
#ifdef __nios2__
  #include "system.h"                 /* LEDS_BASE */
  #include "altera_avalon_pio_regs.h" /* IOWR_ALTERA_AVALON_PIO_DATA */
  static void vs_leds(unsigned v) { IOWR_ALTERA_AVALON_PIO_DATA(LEDS_BASE, v & 0x3ffu); }
#else
  static void vs_leds(unsigned v) { (void)v; }
#endif
// ----------------------------------------------------------------------------
// Transformer model

typedef struct {
    int dim; // transformer dimension
    int hidden_dim; // for ffn layers
    int n_layers; // number of layers
    int n_heads; // number of query heads
    int n_kv_heads; // number of key/value heads (can be < query heads because of multiquery)
    int vocab_size; // vocabulary size, usually 256 (byte-level)
    int seq_len; // max sequence length
} Config;

typedef struct {
    // token embedding table -- int8 rows + one fp32 scale per row (vocab, dim).
    // Also IS the classifier: stories260K has shared_weights=1, so wcls/
    // wcls_scale below just alias these two pointers (see memory_map_weights).
    int8_t* token_embedding_table;
    float*  token_embedding_scale;
    // weights for rmsnorms -- kept fp32, same choice upstream runq.c makes:
    // these are cheap (704 floats total) and softmax/rmsnorm stability is not
    // where the bandwidth problem is.
    float* rms_att_weight; // (layer, dim) rmsnorm weights
    float* rms_ffn_weight; // (layer, dim)
    // weights for matmuls: int8 (layer*d, n) rows + one fp32 scale per row,
    // packed 4-per-32-bit-word (see matmul below). note dim == n_heads * head_size
    int8_t* wq; float* wq_scale; // (layer*dim, dim)
    int8_t* wk; float* wk_scale; // (layer*kv_dim, dim)
    int8_t* wv; float* wv_scale; // (layer*kv_dim, dim)
    int8_t* wo; float* wo_scale; // (layer*dim, dim)
    // weights for ffn
    int8_t* w1; float* w1_scale; // (layer*hidden_dim, dim)
    int8_t* w2; float* w2_scale; // (layer*dim, hidden_dim)
    int8_t* w3; float* w3_scale; // (layer*hidden_dim, dim)
    // final rmsnorm
    float* rms_final_weight; // (dim,)
    // (optional) classifier weights for the logits -- shared with the token
    // embedding table above for stories260K; see memory_map_weights.
    int8_t* wcls; float* wcls_scale;
} TransformerWeights;
typedef struct {
    // current wave of activations
    float *x; // activation at current time stamp (dim,)
    float *xb; // same, but inside a residual branch (dim,)
    float *xb2; // an additional buffer just for convenience (dim,)
    float *hb; // buffer for hidden dimension in the ffn (hidden_dim,)
    float *hb2; // buffer for hidden dimension in the ffn (hidden_dim,)
    float *q; // query (dim,)
    float *k; // key (dim,)
    float *v; // value (dim,)
    float *att; // buffer for scores/attention values (n_heads, seq_len)
    float *logits; // output logits
    // kv cache
    float* key_cache;   // (layer, seq_len, dim)
    float* value_cache; // (layer, seq_len, dim)
} RunState;

typedef struct {
    Config config; // the hyperparameters of the architecture (the blueprint)
    TransformerWeights weights; // the weights of the model
    RunState state; // buffers for the "wave" of activations in the forward pass
    // some more state needed to properly clean up the memory mapping (sigh)
    int fd; // file descriptor for memory mapping
    float* data; // memory mapped data pointer
    ssize_t file_size; // size of the checkpoint file in bytes
} Transformer;

/* Static RunState. Sized for stories260K:
 *   dim 64 | hidden 172 | layers 5 | heads 8 | kv_heads 4 | vocab 512 | seq 512
 * kv_dim = dim * n_kv_heads / n_heads = 32
 * Total ~676 KB -- far too large for the 64 KB on-chip RAM, so the linker MUST
 * place .bss in SDRAM. Getting that wrong hangs with no error message.
 */
#define M_DIM      64
#define M_HIDDEN  172
#define M_LAYERS    5
#define M_HEADS     8
#define M_KVDIM    32
#define M_VOCAB   512
#define M_SEQ     512

static float st_x  [M_DIM];
static float st_xb [M_DIM];
static float st_xb2[M_DIM];
static float st_hb [M_HIDDEN];
static float st_hb2[M_HIDDEN];
static float st_q  [M_DIM];
static float st_key_cache  [M_LAYERS * M_SEQ * M_KVDIM];
static float st_value_cache[M_LAYERS * M_SEQ * M_KVDIM];
static float st_att        [M_HEADS  * M_SEQ];
static float st_logits     [M_VOCAB];

/* Runtime-quantized activation scratch for matmul (see matmul below). Sized
 * to the largest n across all 8 call sites in forward() (172, for w2).
 * aligned(4) is load-bearing: matmul reads it 4 bytes at a time via
 * uint32_t*, and Nios II masks the low address bits of an unaligned word
 * load instead of trapping -- a misaligned buffer would read as
 * plausible-but-wrong numbers, not a crash (the same failure mode the
 * objcopy blob path warns about elsewhere in this project).
 */
static int8_t st_xq[M_HIDDEN] __attribute__((aligned(4)));

void malloc_run_state(RunState* s, Config* p) {
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    /* Refuse to run rather than silently corrupt memory if the linked
     * checkpoint is not the one these arrays were sized for. */
    if (p->dim != M_DIM || p->hidden_dim != M_HIDDEN || p->n_layers != M_LAYERS
     || p->n_heads != M_HEADS || kv_dim != M_KVDIM || p->vocab_size != M_VOCAB
     || p->seq_len != M_SEQ) {
        fputs("checkpoint does not match compiled-in static sizes\n", stderr);
        exit(1);
    }
    memset(st_key_cache,   0, sizeof(st_key_cache));
    memset(st_value_cache, 0, sizeof(st_value_cache));
    s->x = st_x;   s->xb = st_xb;  s->xb2 = st_xb2;
    s->hb = st_hb; s->hb2 = st_hb2; s->q = st_q;
    s->key_cache = st_key_cache;
    s->value_cache = st_value_cache;
    s->att = st_att;
    s->logits = st_logits;
}

void free_run_state(RunState* s) { (void)s; }

/* int8-weight memory map. Walks the blob in exactly the order
 * tools/embed_model.py --q8's quantize() wrote it, mirroring upstream
 * memory_map_weights()'s tensor order but stepping in bytes: each quantized
 * tensor is `rows` int8 columns of `cols` values, immediately followed by
 * `rows` fp32 scales (cols is always a multiple of 4, so this boundary and
 * every subsequent one stays 4-byte aligned with no padding needed). rmsnorm
 * tensors pass through as plain fp32, same as upstream runq.c.
 */
void memory_map_weights(TransformerWeights *w, Config* p, unsigned char* ptr, int shared_weights) {
    int head_size = p->dim / p->n_heads;
    unsigned long long L = p->n_layers;
    int dim = p->dim, hd = p->hidden_dim;
    int kv_dim = p->n_kv_heads * head_size;
    long V = p->vocab_size;
    long r;

    if (!shared_weights) {
        /* Not exercised by stories260K (vocab_size > 0 in its checkpoint) and
         * not implemented in the Python quantizer either -- fail loudly
         * rather than read garbage if this is ever pointed at a different
         * checkpoint. */
        fputs("q8 build only supports a shared classifier (stories260K)\n", stderr);
        exit(1);
    }

    r = V;
    w->token_embedding_table = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->token_embedding_scale = (float*)ptr;  ptr += (size_t)r * sizeof(float);

    w->rms_att_weight = (float*)ptr; ptr += (size_t)L * dim * sizeof(float);

    r = (long)L * dim;
    w->wq = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wq_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * kv_dim;
    w->wk = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wk_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * kv_dim;
    w->wv = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wv_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * dim;
    w->wo = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->wo_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    w->rms_ffn_weight = (float*)ptr; ptr += (size_t)L * dim * sizeof(float);

    r = (long)L * hd;
    w->w1 = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->w1_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * dim;
    w->w2 = (int8_t*)ptr; ptr += (size_t)r * hd;
    w->w2_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    r = (long)L * hd;
    w->w3 = (int8_t*)ptr; ptr += (size_t)r * dim;
    w->w3_scale = (float*)ptr; ptr += (size_t)r * sizeof(float);

    w->rms_final_weight = (float*)ptr; ptr += (size_t)dim * sizeof(float);

    w->wcls = w->token_embedding_table;
    w->wcls_scale = w->token_embedding_scale;
}

void read_checkpoint(char* checkpoint, Config* config, TransformerWeights* weights,
                     int* fd, float** data, ssize_t* file_size) {
    /* BARE METAL, int8 weights: no fopen, no fseek, no mmap. Layout written by
     * tools/embed_model.py --q8: 7-int Config header, then a magic uint32,
     * then the quantized tensors in memory_map_weights order below. */
    const unsigned char* blob = MODEL_BLOB;
    memcpy(config, blob, sizeof(Config));
    int shared_weights = config->vocab_size > 0 ? 1 : 0;
    config->vocab_size = abs(config->vocab_size);
    *fd = -1;
    *file_size = 0;
    *data = (float*)(void*)blob;

    uint32_t magic;
    memcpy(&magic, blob + sizeof(Config), sizeof(magic));
    if (magic != 0x51385653u) {
        /* Refuse to run rather than silently misread a stale/mismatched blob --
         * same philosophy as malloc_run_state's size guard below. */
        fputs("q8 blob magic mismatch -- stale or wrong model260k_q8.h\n", stderr);
        exit(1);
    }
    unsigned char* weights_ptr = (unsigned char*)blob + sizeof(Config) + sizeof(magic);
    memory_map_weights(weights, config, weights_ptr, shared_weights);
}

void build_transformer(Transformer *t, char* checkpoint_path) {
    // read in the Config and the Weights from the checkpoint
    read_checkpoint(checkpoint_path, &t->config, &t->weights, &t->fd, &t->data, &t->file_size);
    // allocate the RunState buffers
    malloc_run_state(&t->state, &t->config);
}

void free_transformer(Transformer* t) { (void)t; }

// ----------------------------------------------------------------------------
// neural net blocks; the dynamics of the Transformer

void rmsnorm(float* o, float* x, float* weight, int size) {
    // calculate sum of squares
    float ss = 0.0f;
    for (int j = 0; j < size; j++) {
        ss += x[j] * x[j];
    }
    ss /= size;
    ss += 1e-5f;
    ss = 1.0f / sqrtf(ss);
    // normalize and scale
    for (int j = 0; j < size; j++) {
        o[j] = weight[j] * (ss * x[j]);
    }
}

void softmax(float* x, int size) {
    // find max value (for numerical stability)
    float max_val = x[0];
    for (int i = 1; i < size; i++) {
        if (x[i] > max_val) {
            max_val = x[i];
        }
    }
    // exp and sum
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        x[i] = expf(x[i] - max_val);
        sum += x[i];
    }
    // normalize
    for (int i = 0; i < size; i++) {
        x[i] /= sum;
    }
}

void matmul(float* xout, float* x, int8_t* w, float* wscale, int n, int d) {
    // int8 W (d,n) @ x (n,) -> xout (d,), one fp32 scale per row of W.
    // Not upstream -- see docs/HARDWARE-RESULTS.md: this board is
    // bandwidth-bound (no data cache, 16-bit SDRAM), so every uncached load
    // here is packed 4 values to a 32-bit word instead of 1. n is always a
    // multiple of 4 (64 or 172 for stories260K; asserted in the Python
    // quantizer), so there is no tail case to handle.
    //
    // x is quantized into st_xq once per call, O(n) against the O(n*d) cost
    // of the loop below -- see MALLOC_STATE_Q8 for why st_xq must stay
    // 4-byte aligned.
    float xmax = 0.0f;
    for (int j = 0; j < n; j++) {
        float a = fabsf(x[j]);
        if (a > xmax) xmax = a;
    }
    float xs = (xmax > 0.0f) ? (xmax / 127.0f) : 1.0f;
    for (int j = 0; j < n; j++) {
        int q = (int)roundf(x[j] / xs);
        q = q > 127 ? 127 : (q < -127 ? -127 : q);
        st_xq[j] = (int8_t)q;
    }

    int i;
    #pragma omp parallel for private(i)
    for (i = 0; i < d; i++) {
        const uint32_t* wp = (const uint32_t*)(w + (size_t)i * n);
        const uint32_t* xp = (const uint32_t*)st_xq;
        int32_t ival = 0;
        for (int j = 0; j < n >> 2; j++) {
            uint32_t wpk = wp[j];
            uint32_t xpk = xp[j];
            ival += (int32_t)(int8_t)( wpk        & 0xff) * (int32_t)(int8_t)( xpk        & 0xff);
            ival += (int32_t)(int8_t)((wpk >>  8) & 0xff) * (int32_t)(int8_t)((xpk >>  8) & 0xff);
            ival += (int32_t)(int8_t)((wpk >> 16) & 0xff) * (int32_t)(int8_t)((xpk >> 16) & 0xff);
            ival += (int32_t)(int8_t)((wpk >> 24) & 0xff) * (int32_t)(int8_t)((xpk >> 24) & 0xff);
        }
        xout[i] = (float)ival * wscale[i] * xs;
    }
}

float* forward(Transformer* transformer, int token, int pos) {

    // a few convenience variables
    Config* p = &transformer->config;
    TransformerWeights* w = &transformer->weights;
    RunState* s = &transformer->state;
    float *x = s->x;
    int dim = p->dim;
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int kv_mul = p->n_heads / p->n_kv_heads; // integer multiplier of the kv sharing in multiquery
    int hidden_dim =  p->hidden_dim;
    int head_size = dim / p->n_heads;

    // copy the token embedding into x -- dequantized, since x is fp32
    // everywhere downstream (RoPE/attention/softmax are all still upstream
    // fp32 math; only matmul's inputs are int8).
    {
        int8_t* content_row = w->token_embedding_table + (size_t)token * dim;
        float   row_scale    = w->token_embedding_scale[token];
        for (int j = 0; j < dim; j++) x[j] = content_row[j] * row_scale;
    }

    // forward all the layers
    for(unsigned long long l = 0; l < p->n_layers; l++) {

        // attention rmsnorm
        rmsnorm(s->xb, x, w->rms_att_weight + l*dim, dim);

        // key and value point to the kv cache
        int loff = l * p->seq_len * kv_dim; // kv cache layer offset for convenience
        s->k = s->key_cache + loff + pos * kv_dim;
        s->v = s->value_cache + loff + pos * kv_dim;

        // qkv matmuls for this position
        matmul(s->q, s->xb, w->wq + l*dim*dim, w->wq_scale + l*dim, dim, dim);
        matmul(s->k, s->xb, w->wk + l*dim*kv_dim, w->wk_scale + l*kv_dim, dim, kv_dim);
        matmul(s->v, s->xb, w->wv + l*dim*kv_dim, w->wv_scale + l*kv_dim, dim, kv_dim);

        // RoPE relative positional encoding: complex-valued rotate q and k in each head
        for (int i = 0; i < dim; i+=2) {
            int head_dim = i % head_size;
            float freq = 1.0f / powf(10000.0f, head_dim / (float)head_size);
            float val = pos * freq;
            float fcr = cosf(val);
            float fci = sinf(val);
            int rotn = i < kv_dim ? 2 : 1; // how many vectors? 2 = q & k, 1 = q only
            for (int v = 0; v < rotn; v++) {
                float* vec = v == 0 ? s->q : s->k; // the vector to rotate (query or key)
                float v0 = vec[i];
                float v1 = vec[i+1];
                vec[i]   = v0 * fcr - v1 * fci;
                vec[i+1] = v0 * fci + v1 * fcr;
            }
        }

        // multihead attention. iterate over all heads
        int h;
        #pragma omp parallel for private(h)
        for (h = 0; h < p->n_heads; h++) {
            // get the query vector for this head
            float* q = s->q + h * head_size;
            // attention scores for this head
            float* att = s->att + h * p->seq_len;
            // iterate over all timesteps, including the current one
            for (int t = 0; t <= pos; t++) {
                // get the key vector for this head and at this timestep
                float* k = s->key_cache + loff + t * kv_dim + (h / kv_mul) * head_size;
                // calculate the attention score as the dot product of q and k
                float score = 0.0f;
                for (int i = 0; i < head_size; i++) {
                    score += q[i] * k[i];
                }
                score /= sqrtf(head_size);
                // save the score to the attention buffer
                att[t] = score;
            }

            // softmax the scores to get attention weights, from 0..pos inclusively
            softmax(att, pos + 1);

            // weighted sum of the values, store back into xb
            float* xb = s->xb + h * head_size;
            memset(xb, 0, head_size * sizeof(float));
            for (int t = 0; t <= pos; t++) {
                // get the value vector for this head and at this timestep
                float* v = s->value_cache + loff + t * kv_dim + (h / kv_mul) * head_size;
                // get the attention weight for this timestep
                float a = att[t];
                // accumulate the weighted value into xb
                for (int i = 0; i < head_size; i++) {
                    xb[i] += a * v[i];
                }
            }
        }

        // final matmul to get the output of the attention
        matmul(s->xb2, s->xb, w->wo + l*dim*dim, w->wo_scale + l*dim, dim, dim);

        // residual connection back into x
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb2[i];
        }

        // ffn rmsnorm
        rmsnorm(s->xb, x, w->rms_ffn_weight + l*dim, dim);

        // Now for FFN in PyTorch we have: self.w2(F.silu(self.w1(x)) * self.w3(x))
        // first calculate self.w1(x) and self.w3(x)
        matmul(s->hb, s->xb, w->w1 + l*dim*hidden_dim, w->w1_scale + l*hidden_dim, dim, hidden_dim);
        matmul(s->hb2, s->xb, w->w3 + l*dim*hidden_dim, w->w3_scale + l*hidden_dim, dim, hidden_dim);

        // SwiGLU non-linearity
        for (int i = 0; i < hidden_dim; i++) {
            float val = s->hb[i];
            // silu(x)=x*σ(x), where σ(x) is the logistic sigmoid
            val *= (1.0f / (1.0f + expf(-val)));
            // elementwise multiply with w3(x)
            val *= s->hb2[i];
            s->hb[i] = val;
        }

        // final matmul to get the output of the ffn
        matmul(s->xb, s->hb, w->w2 + l*dim*hidden_dim, w->w2_scale + l*dim, hidden_dim, dim);

        // residual connection
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb[i];
        }
    }

    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);

    // classifier into logits
    matmul(s->logits, x, w->wcls, w->wcls_scale, p->dim, p->vocab_size);
    return s->logits;
}

// The Byte Pair Encoding (BPE) Tokenizer that translates strings <-> tokens

typedef struct {
    char *str;
    int id;
} TokenIndex;

typedef struct {
    char** vocab;
    float* vocab_scores;
    TokenIndex *sorted_vocab;
    int vocab_size;
    unsigned int max_token_length;
    unsigned char byte_pieces[512]; // stores all single-byte strings
} Tokenizer;

int compare_tokens(const void *a, const void *b) {
    return strcmp(((TokenIndex*)a)->str, ((TokenIndex*)b)->str);
}

void build_tokenizer(Tokenizer* t, char* tokenizer_path, int vocab_size) {
    // i should have written the vocab_size into the tokenizer file... sigh
    t->vocab_size = vocab_size;
    // malloc space to hold the scores and the strings
    t->vocab = (char**)amalloc(vocab_size * sizeof(char*));
    t->vocab_scores = (float*)amalloc(vocab_size * sizeof(float));
    t->sorted_vocab = NULL; // initialized lazily
    for (int i = 0; i < 256; i++) {
        t->byte_pieces[i * 2] = (unsigned char)i;
        t->byte_pieces[i * 2 + 1] = '\0';
    }
    /* BARE METAL: walk the linked blob instead of fread-ing a file. */
    const unsigned char* tb = TOKEN_BLOB;
    size_t off = 0;
    memcpy(&t->max_token_length, tb + off, sizeof(int)); off += sizeof(int);
    int len;
    for (int i = 0; i < vocab_size; i++) {
        memcpy(t->vocab_scores + i, tb + off, sizeof(float)); off += sizeof(float);
        memcpy(&len, tb + off, sizeof(int)); off += sizeof(int);
        t->vocab[i] = (char *)amalloc(len + 1);
        memcpy(t->vocab[i], tb + off, len); off += len;
        t->vocab[i][len] = '\0'; // add the string terminating token
    }
}

void free_tokenizer(Tokenizer* t) { (void)t; }

char* decode(Tokenizer* t, int prev_token, int token) {
    char *piece = t->vocab[token];
    // following BOS (1) token, sentencepiece decoder strips any leading whitespace (see PR #89)
    if (prev_token == 1 && piece[0] == ' ') { piece++; }
    // careful, some tokens designate raw bytes, and look like e.g. '<0x01>'
    // parse this and convert and return the actual byte
    unsigned char byte_val;
    if (sscanf(piece, "<0x%02hhX>", &byte_val) == 1) {
        piece = (char*)t->byte_pieces + byte_val * 2;
    }
    return piece;
}

void safe_printf(char *piece) {
    // piece might be a raw byte token, and we only want to print printable chars or whitespace
    // because some of the other bytes can be various control codes, backspace, etc.
    if (piece == NULL) { return; }
    if (piece[0] == '\0') { return; }
    if (piece[1] == '\0') {
        unsigned char byte_val = piece[0];
        if (!(isprint(byte_val) || isspace(byte_val))) {
            return; // bad byte, don't print it
        }
    }
    printf("%s", piece);
}

int str_lookup(char *str, TokenIndex *sorted_vocab, int vocab_size) {
    // efficiently find the perfect match for str in vocab, return its index or -1 if not found
    TokenIndex tok = { .str = str }; // acts as the key to search for
    TokenIndex *res = bsearch(&tok, sorted_vocab, vocab_size, sizeof(TokenIndex), compare_tokens);
    return res != NULL ? res->id : -1;
}

void encode(Tokenizer* t, char *text, int8_t bos, int8_t eos, int *tokens, int *n_tokens) {
    // encode the string text (input) into an upper-bound preallocated tokens[] array
    // bos != 0 means prepend the BOS token (=1), eos != 0 means append the EOS token (=2)
    if (text == NULL) { fprintf(stderr, "cannot encode NULL text\n"); exit(EXIT_FAILURE); }

    if (t->sorted_vocab == NULL) {
        // lazily malloc and sort the vocabulary
        t->sorted_vocab = amalloc(t->vocab_size * sizeof(TokenIndex));
        for (int i = 0; i < t->vocab_size; i++) {
            t->sorted_vocab[i].str = t->vocab[i];
            t->sorted_vocab[i].id = i;
        }
        qsort(t->sorted_vocab, t->vocab_size, sizeof(TokenIndex), compare_tokens);
    }

    // create a temporary buffer that will store merge candidates of always two consecutive tokens
    // *2 for concat, +1 for null terminator +2 for UTF8 (in case max_token_length is 1)
    char* str_buffer = amalloc((t->max_token_length*2 +1 +2) * sizeof(char));
    size_t str_len = 0;

    // start at 0 tokens
    *n_tokens = 0;

    // add optional BOS (=1) token, if desired
    if (bos) tokens[(*n_tokens)++] = 1;

    // add_dummy_prefix is true by default
    // so prepend a dummy prefix token to the input string, but only if text != ""
    // TODO: pretty sure this isn't correct in the general case but I don't have the
    // energy to read more of the sentencepiece code to figure out what it's doing
    if (text[0] != '\0') {
        int dummy_prefix = str_lookup(" ", t->sorted_vocab, t->vocab_size);
        tokens[(*n_tokens)++] = dummy_prefix;
    }

    // Okay UTF-8 time. This will get messy. Here is the reference from Wikipedia:
    // Code point ↔ UTF-8 conversion
    // First code point	Last code point	Byte 1	Byte 2	Byte 3	Byte 4
    // U+0000	U+007F	    0xxxxxxx
    // U+0080	U+07FF	    110xxxxx	10xxxxxx
    // U+0800	U+FFFF	    1110xxxx	10xxxxxx	10xxxxxx
    // U+10000	U+10FFFF    11110xxx	10xxxxxx	10xxxxxx	10xxxxxx

    // process the raw (UTF-8) byte sequence of the input string
    for (char *c = text; *c != '\0'; c++) {

        // reset buffer if the current byte is ASCII or a leading byte
        // 0xC0 is 11000000, so (*c & 0xC0) keeps the first 2 bits and zeros the rest
        // 0x80 is 10000000
        // in UTF-8, all continuation bytes start with "10" in first two bits
        // so in English this is: "if this byte is not a continuation byte"
        if ((*c & 0xC0) != 0x80) {
            // this byte must be either a leading byte (11...) or an ASCII char (0x...)
            // => reset our location, as we're starting a new UTF-8 codepoint
            str_len = 0;
        }

        // append the current byte to the buffer
        str_buffer[str_len++] = *c; // ++ is post-increment, incremented after this line
        str_buffer[str_len] = '\0';

        // while the next character is a continuation byte, continue appending
        // but if there are too many of them, just stop to avoid overruning str_buffer size.
        if ((*(c+1) & 0xC0) == 0x80 && str_len < 4) {
            continue;
        }

        // ok c+1 is not a continuation byte, so we've read in a full codepoint
        int id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);

        if (id != -1) {
            // we found this codepoint in vocab, add it as a token
            tokens[(*n_tokens)++] = id;
        } else {
            // byte_fallback encoding: just encode each byte as a token
            // +3 is here because the first 3 vocab elements are <unk>, <s>, </s>
            // so the individual bytes only start at index 3
            for (int i=0; i < str_len; i++) {
                tokens[(*n_tokens)++] = (unsigned char)str_buffer[i] + 3;
            }
        }
        str_len = 0; // protect against a sequence of stray UTF8 continuation bytes
    }

    // merge the best consecutive pair each iteration, according the scores in vocab_scores
    while (1) {
        float best_score = -1e10;
        int best_id = -1;
        int best_idx = -1;

        for (int i=0; i < (*n_tokens-1); i++) {
            // check if we can merge the pair (tokens[i], tokens[i+1])
            sprintf(str_buffer, "%s%s", t->vocab[tokens[i]], t->vocab[tokens[i+1]]);
            int id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);
            if (id != -1 && t->vocab_scores[id] > best_score) {
                // this merge pair exists in vocab! record its score and position
                best_score = t->vocab_scores[id];
                best_id = id;
                best_idx = i;
            }
        }

        if (best_idx == -1) {
            break; // we couldn't find any more pairs to merge, so we're done
        }

        // merge the consecutive pair (best_idx, best_idx+1) into new token best_id
        tokens[best_idx] = best_id;
        // delete token at position best_idx+1, shift the entire sequence back 1
        for (int i = best_idx+1; i < (*n_tokens-1); i++) {
            tokens[i] = tokens[i+1];
        }
        (*n_tokens)--; // token length decreased
    }

    // add optional EOS (=2) token, if desired
    if (eos) tokens[(*n_tokens)++] = 2;

}

// ----------------------------------------------------------------------------
// The Sampler, which takes logits and returns a sampled token
// sampling can be done in a few ways: greedy argmax, sampling, top-p sampling

typedef struct {
    float prob;
    int index;
} ProbIndex; // struct used when sorting probabilities during top-p sampling

typedef struct {
    int vocab_size;
    ProbIndex* probindex; // buffer used in top-p sampling
    float temperature;
    float topp;
    unsigned long long rng_state;
} Sampler;

int sample_argmax(float* probabilities, int n) {
    // return the index that has the highest probability
    int max_i = 0;
    float max_p = probabilities[0];
    for (int i = 1; i < n; i++) {
        if (probabilities[i] > max_p) {
            max_i = i;
            max_p = probabilities[i];
        }
    }
    return max_i;
}

int sample_mult(float* probabilities, int n, float coin) {
    // sample index from probabilities (they must sum to 1!)
    // coin is a random number in [0, 1), usually from random_f32()
    float cdf = 0.0f;
    for (int i = 0; i < n; i++) {
        cdf += probabilities[i];
        if (coin < cdf) {
            return i;
        }
    }
    return n - 1; // in case of rounding errors
}

int compare(const void* a, const void* b) {
    ProbIndex* a_ = (ProbIndex*) a;
    ProbIndex* b_ = (ProbIndex*) b;
    if (a_->prob > b_->prob) return -1;
    if (a_->prob < b_->prob) return 1;
    return 0;
}

int sample_topp(float* probabilities, int n, float topp, ProbIndex* probindex, float coin) {
    // top-p sampling (or "nucleus sampling") samples from the smallest set of
    // tokens that exceed probability topp. This way we never sample tokens that
    // have very low probabilities and are less likely to go "off the rails".
    // coin is a random number in [0, 1), usually from random_f32()

    int n0 = 0;
    // quicksort indices in descending order of probabilities
    // values smaller than (1 - topp) / (n - 1) cannot be part of the result
    // so for efficiency we crop these out as candidates before sorting
    const float cutoff = (1.0f - topp) / (n - 1);
    for (int i = 0; i < n; i++) {
        if (probabilities[i] >= cutoff) {
            probindex[n0].index = i;
            probindex[n0].prob = probabilities[i];
            n0++;
        }
    }
    qsort(probindex, n0, sizeof(ProbIndex), compare);

    // truncate the list where cumulative probability exceeds topp
    float cumulative_prob = 0.0f;
    int last_idx = n0 - 1; // in case of rounding errors consider all elements
    for (int i = 0; i < n0; i++) {
        cumulative_prob += probindex[i].prob;
        if (cumulative_prob > topp) {
            last_idx = i;
            break; // we've exceeded topp by including last_idx
        }
    }

    // sample from the truncated list
    float r = coin * cumulative_prob;
    float cdf = 0.0f;
    for (int i = 0; i <= last_idx; i++) {
        cdf += probindex[i].prob;
        if (r < cdf) {
            return probindex[i].index;
        }
    }
    return probindex[last_idx].index; // in case of rounding errors
}

void build_sampler(Sampler* sampler, int vocab_size, float temperature, float topp, unsigned long long rng_seed) {
    sampler->vocab_size = vocab_size;
    sampler->temperature = temperature;
    sampler->topp = topp;
    sampler->rng_state = rng_seed;
    // buffer only used with nucleus sampling; may not need but it's ~small
    sampler->probindex = amalloc(sampler->vocab_size * sizeof(ProbIndex));
}

void free_sampler(Sampler* sampler) { (void)sampler; }

unsigned int random_u32(unsigned long long *state) {
    // xorshift rng: https://en.wikipedia.org/wiki/Xorshift#xorshift.2A
    *state ^= *state >> 12;
    *state ^= *state << 25;
    *state ^= *state >> 27;
    return (*state * 0x2545F4914F6CDD1Dull) >> 32;
}
float random_f32(unsigned long long *state) { // random float32 in [0,1)
    return (random_u32(state) >> 8) / 16777216.0f;
}

int sample(Sampler* sampler, float* logits) {
    // sample the token given the logits and some hyperparameters
    int next;
    if (sampler->temperature == 0.0f) {
        // greedy argmax sampling: take the token with the highest probability
        next = sample_argmax(logits, sampler->vocab_size);
    } else {
        // apply the temperature to the logits
        for (int q=0; q<sampler->vocab_size; q++) { logits[q] /= sampler->temperature; }
        // apply softmax to the logits to get the probabilities for next token
        softmax(logits, sampler->vocab_size);
        // flip a (float) coin (this is our source of entropy for sampling)
        float coin = random_f32(&sampler->rng_state);
        // we sample from this distribution to get the next token
        if (sampler->topp <= 0 || sampler->topp >= 1) {
            // simply sample from the predicted probability distribution
            next = sample_mult(logits, sampler->vocab_size, coin);
        } else {
            // top-p (nucleus) sampling, clamping the least likely tokens to zero
            next = sample_topp(logits, sampler->vocab_size, sampler->topp, sampler->probindex, coin);
        }
    }
    return next;
}

// ----------------------------------------------------------------------------
// utilities: time

long time_in_ms() {
    /* No clock_gettime on bare metal. Returns 0 so the tok/s line is skipped;
     * Justin measures wall-clock with a stopwatch, which is the honest number
     * to put on a slide anyway. */
    return 0;
}

// ----------------------------------------------------------------------------
// generation loop

void generate(Transformer *transformer, Tokenizer *tokenizer, Sampler *sampler, char *prompt, int steps) {
    char *empty_prompt = "";
    if (prompt == NULL) { prompt = empty_prompt; }

    // encode the (string) prompt into tokens sequence
    int num_prompt_tokens = 0;
    int* prompt_tokens = (int*)amalloc((strlen(prompt)+3) * sizeof(int)); // +3 for '\0', ?BOS, ?EOS
    encode(tokenizer, prompt, 1, 0, prompt_tokens, &num_prompt_tokens);
    if (num_prompt_tokens < 1) {
        fprintf(stderr, "something is wrong, expected at least 1 prompt token\n");
        exit(EXIT_FAILURE);
    }

    // start the main loop
    long start = 0;  // used to time our code, only initialized after first iteration
    int next;        // will store the next token in the sequence
    int token = prompt_tokens[0]; // kick off with the first token in the prompt
    int pos = 0;     // position in the sequence
    while (pos < steps) {

        // forward the transformer to get logits for the next token
        float* logits = forward(transformer, token, pos);

        // advance the state machine
        if (pos < num_prompt_tokens - 1) {
            // if we are still processing the input prompt, force the next prompt token
            next = prompt_tokens[pos + 1];
        } else {
            // otherwise sample the next token from the logits
            next = sample(sampler, logits);
        }
        pos++;

        // data-dependent terminating condition: the BOS (=1) token delimits sequences
        if (next == 1) { break; }

        // print the token as string, decode it with the Tokenizer object
        char* piece = decode(tokenizer, token, next);
        safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes
        fflush(stdout);
        vs_leds(pos);  /* SIGN OF LIFE: token counter in binary on LEDR[9:0] */
        token = next;

        // init the timer here because the first iteration can be slower
        if (start == 0) { start = time_in_ms(); }
    }
    printf("\n");

    // report achieved tok/s (pos-1 because the timer starts after first iteration)
    if (pos > 1) {
        long end = time_in_ms();
        long ms = end - start;
        if (ms > 0) fprintf(stderr, "achieved tok/s: %ld (x100)\n", (long)(pos-1)*100000L/ms);
    }

}

void read_stdin(const char* guide, char* buffer, size_t bufsize) {
    // read a line from stdin, up to but not including \n
    printf("%s", guide);
    if (fgets(buffer, bufsize, stdin) != NULL) {
        size_t len = strlen(buffer);
        if (len > 0 && buffer[len - 1] == '\n') {
            buffer[len - 1] = '\0'; // strip newline
        }
    }
}

// ----------------------------------------------------------------------------
// chat loop
// I manually inspected the tokens for a few chat conversations compared to
// python reference and that seemed ok, but this was not thoroughly tested and
// is not safely implemented, it's more a proof of concept atm.

void chat(Transformer *transformer, Tokenizer *tokenizer, Sampler *sampler,
          char *cli_user_prompt, char *cli_system_prompt, int steps) {

    // buffers for reading the system prompt and user prompt from stdin
    // you'll notice they are soomewhat haphazardly and unsafely set atm
    char system_prompt[512];
    char user_prompt[512];
    char rendered_prompt[1152];
    int num_prompt_tokens = 0;
    int* prompt_tokens = (int*)amalloc(1152 * sizeof(int));
    int user_idx;

    // start the main loop
    int8_t user_turn = 1; // user starts
    int next;        // will store the next token in the sequence
    int token;       // stores the current token to feed into the transformer
    int prev_token;
    int pos = 0;     // position in the sequence
    while (pos < steps) {

        // when it is the user's turn to contribute tokens to the dialog...
        if (user_turn) {
            // get the (optional) system prompt at position 0
            if (pos == 0) {
                // at position 0, the user can also contribute a system prompt
                if (cli_system_prompt == NULL) {
                    // system prompt was not passed in, attempt to get it from stdin
                    read_stdin("Enter system prompt (optional): ", system_prompt, sizeof(system_prompt));
                } else {
                    // system prompt was passed in, use it
                    strcpy(system_prompt, cli_system_prompt);
                }
            }
            // get the user prompt
            if (pos == 0 && cli_user_prompt != NULL) {
                // user prompt for position 0 was passed in, use it
                strcpy(user_prompt, cli_user_prompt);
            } else {
                // otherwise get user prompt from stdin
                read_stdin("User: ", user_prompt, sizeof(user_prompt));
            }
            // render user/system prompts into the Llama 2 Chat schema
            if (pos == 0 && system_prompt[0] != '\0') {
                char system_template[] = "[INST] <<SYS>>\n%s\n<</SYS>>\n\n%s [/INST]";
                sprintf(rendered_prompt, system_template, system_prompt, user_prompt);
            } else {
                char user_template[] = "[INST] %s [/INST]";
                sprintf(rendered_prompt, user_template, user_prompt);
            }
            // encode the rendered prompt into tokens
            encode(tokenizer, rendered_prompt, 1, 0, prompt_tokens, &num_prompt_tokens);
            user_idx = 0; // reset the user index
            user_turn = 0;
            printf("Assistant: ");
        }

        // determine the token to pass into the transformer next
        if (user_idx < num_prompt_tokens) {
            // if we are still processing the input prompt, force the next prompt token
            token = prompt_tokens[user_idx++];
        } else {
            // otherwise use the next token sampled from previous turn
            token = next;
        }
        // EOS (=2) token ends the Assistant turn
        if (token == 2) { user_turn = 1; }

        // forward the transformer to get logits for the next token
        float* logits = forward(transformer, token, pos);
        next = sample(sampler, logits);
        pos++;

        if (user_idx >= num_prompt_tokens && next != 2) {
            // the Assistant is responding, so print its output
            char* piece = decode(tokenizer, token, next);
            safe_printf(piece); // same as printf("%s", piece), but skips "unsafe" bytes
            fflush(stdout);
        }
        if (next == 2) { printf("\n"); }
    }
    printf("\n");
}


// ----------------------------------------------------------------------------
// CLI, include only if not testing
#ifndef TESTING

void error_usage() {
    fprintf(stderr, "Usage:   run <checkpoint> [options]\n");
    fprintf(stderr, "Example: run model.bin -n 256 -i \"Once upon a time\"\n");
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -t <float>  temperature in [0,inf], default 1.0\n");
    fprintf(stderr, "  -p <float>  p value in top-p (nucleus) sampling in [0,1] default 0.9\n");
    fprintf(stderr, "  -s <int>    random seed, default time(NULL)\n");
    fprintf(stderr, "  -n <int>    number of steps to run for, default 256. 0 = max_seq_len\n");
    fprintf(stderr, "  -i <string> input prompt\n");
    fprintf(stderr, "  -z <string> optional path to custom tokenizer\n");
    fprintf(stderr, "  -m <string> mode: generate|chat, default: generate\n");
    fprintf(stderr, "  -y <string> (optional) system prompt in chat mode\n");
    exit(EXIT_FAILURE);
}

int main(void) {
    /* BARE METAL: no argv. Everything is fixed at compile time.
     * Unbuffered stdout is not cosmetic -- without it newlib buffers the whole
     * generation and the board looks dead for 30 seconds, then dumps at once. */
    setvbuf(stdout, NULL, _IONBF, 0);
    vs_leds(0x3ff);   /* all on while the tokenizer builds -- the board is not dead */

    char* checkpoint_path = NULL;
    char* tokenizer_path  = NULL;
    float temperature = 1.0f;
    float topp        = 0.9f;
    int   steps       = 256;
    char* prompt      = NULL;
    unsigned long long rng_seed = 42;   /* fixed: reproducible on stage */
    char* mode        = "generate";
    char* system_prompt = NULL;

    Transformer transformer;
    build_transformer(&transformer, checkpoint_path);
    if (steps == 0 || steps > transformer.config.seq_len) steps = transformer.config.seq_len;

    Tokenizer tokenizer;
    build_tokenizer(&tokenizer, tokenizer_path, transformer.config.vocab_size);

    Sampler sampler;
    build_sampler(&sampler, transformer.config.vocab_size, temperature, topp, rng_seed);

    generate(&transformer, &tokenizer, &sampler, prompt, steps);
    vs_leds(0x3ff);   /* all on, held: generation finished cleanly */

    free_sampler(&sampler);
    free_tokenizer(&tokenizer);
    free_transformer(&transformer);
    return 0;
}
#endif
